Repository leonbartz/SUD-Rollins, pull requests merged in 2023-02, with the labels that each got.

#30 Sud 1 object class
  leistungstraeger-app/src/main/java/item/AbstractItem.java
  leistungstraeger-app/src/main/java/object/AbstractObject.java
  leistungstraeger-app/src/main/java/object/MovingAbstractObject.java
  leistungstraeger-app/src/main/java/object/interaction/HasInventory.java
  leistungstraeger-app/src/main/java/object/interaction/IsAttackable.java
  leistungstraeger-app/src/main/java/object/interaction/canAttack.java
  leistungstraeger-app/src/main/java/object/interaction/isOpenable.java
Labels: backend

#52 SUD-42-US5_Game_Bootstrap
  leistungstraeger-app/src/main/java/DesktopLauncher.java
  leistungstraeger-app/src/main/java/application/DesktopLauncher.java
  leistungstraeger-app/src/main/java/application/core/map/MapView.java
  leistungstraeger-app/src/main/java/application/core/window/Window.java
  leistungstraeger-app/src/main/java/application/helper/ImageLoader.java
  leistungstraeger-app/src/main/java/core/Item/AbstractItem.java
  leistungstraeger-app/src/main/java/core/Item/Item.java
  leistungstraeger-app/src/main/java/core/Item/NoItem.java
  leistungstraeger-app/src/main/java/core/Item/Sword.java
  leistungstraeger-app/src/main/java/core/character/Combatable.java
  leistungstraeger-app/src/main/java/core/character/GameCharacter.java
  leistungstraeger-app/src/main/java/core/character/GameObject.java
  leistungstraeger-app/src/main/java/core/client/Client.java
  leistungstraeger-app/src/main/java/core/client/ClientSocket.java
  leistungstraeger-app/src/main/java/core/game/Game.java
  leistungstraeger-app/src/main/java/core/game/Turn.java
  leistungstraeger-app/src/main/java/core/game/TurnSocket.java
  leistungstraeger-app/src/main/java/core/object/AbstractObject.java
  leistungstraeger-app/src/main/java/core/object/MovingAbstractObject.java
  leistungstraeger-app/src/main/java/core/object/interaction/HasInventory.java
  leistungstraeger-app/src/main/java/core/object/interaction/IsAttackable.java
  leistungstraeger-app/src/main/java/core/object/interaction/canAttack.java
  leistungstraeger-app/src/main/java/core/object/interaction/isOpenable.java
  leistungstraeger-app/src/main/java/core/playingfield/map/GameMap.java
  leistungstraeger-app/src/main/java/core/playingfield/map/GameMapView.java
  leistungstraeger-app/src/main/java/core/window/Window.java
  leistungstraeger-app/src/main/java/helpers/Observer/Observer.java
  leistungstraeger-app/src/main/java/helpers/Observer/Subject.java
  leistungstraeger-app/src/main/java/helpers/Socket/Socket.java
  leistungstraeger-app/src/main/java/helpers/charactergenerator/CharacterGenerator.java
  leistungstraeger-app/src/main/java/helpers/collections/RingList.java
  leistungstraeger-app/src/main/java/helpers/collections/RingListElement.java
  leistungstraeger-app/src/main/java/helpers/command/AttackCommand.java
  leistungstraeger-app/src/main/java/helpers/command/CommandManager.java
  leistungstraeger-app/src/main/java/helpers/command/EndTurnCommand.java
  leistungstraeger-app/src/main/java/helpers/command/GameCommand.java
  leistungstraeger-app/src/main/java/helpers/command/GameCommandSocket.java
  leistungstraeger-app/src/main/java/helpers/command/MoveCommand.java
  leistungstraeger-app/src/main/java/helpers/coordinate/CardinalDirection.java
  leistungstraeger-app/src/main/java/helpers/coordinate/Coordinate.java
  leistungstraeger-app/src/main/java/helpers/image/ImageController.java
  leistungstraeger-app/src/main/java/helpers/keyboard/KeyboardHandler.java
  leistungstraeger-app/src/main/java/helpers/mouse/MapMouseInputHandler.java
  leistungstraeger-app/src/main/resources/character_images/character.png
  leistungstraeger-app/src/main/resources/room_images/room.png
Labels: frontend, backend, US5

#40 SUD-2: Implementation Item/ItemStash
  leistungstraeger-app/src/main/java/DesktopLauncher.java
  leistungstraeger-app/src/main/java/core/Item/AbstractItem.java
  leistungstraeger-app/src/main/java/core/Item/Item.java
  leistungstraeger-app/src/main/java/core/Item/NoItem.java
  leistungstraeger-app/src/main/java/core/Item/Sword.java
  leistungstraeger-app/src/main/java/core/character/GameCharacter.java
  leistungstraeger-app/src/main/java/core/character/GameObject.java
  leistungstraeger-app/src/main/java/core/game/Game.java
  leistungstraeger-app/src/main/java/core/game/Turn.java
  leistungstraeger-app/src/main/java/core/item/AbstractItem.java
  leistungstraeger-app/src/main/java/core/item/AbstractModifyingItem.java
  leistungstraeger-app/src/main/java/core/item/ItemStash.java
  leistungstraeger-app/src/main/java/core/item/ItemUtils.java
  leistungstraeger-app/src/main/java/core/item/implementations/NoItem.java
  leistungstraeger-app/src/main/java/core/item/implementations/Sword.java
  leistungstraeger-app/src/main/java/core/item/modifier/Modifier.java
  leistungstraeger-app/src/main/java/core/item/modifier/ModifierIdentifier.java
  leistungstraeger-app/src/main/java/core/object/AbstractObject.java
  leistungstraeger-app/src/main/java/core/object/MovingAbstractObject.java
  leistungstraeger-app/src/main/java/core/object/implementation/Combatable.java
  leistungstraeger-app/src/main/java/core/object/implementation/GameCharacter.java
  leistungstraeger-app/src/main/java/core/object/interaction/HasInventory.java
  leistungstraeger-app/src/main/java/core/object/interaction/IsAttackable.java
  leistungstraeger-app/src/main/java/core/object/interaction/canAttack.java
  leistungstraeger-app/src/main/java/core/object/interaction/isOpenable.java
  leistungstraeger-app/src/main/java/core/playingfield/map/GameMap.java
  leistungstraeger-app/src/main/java/core/playingfield/map/GameMapView.java
  leistungstraeger-app/src/main/java/helpers/charactergenerator/CharacterGenerator.java
  leistungstraeger-app/src/main/java/helpers/command/AttackCommand.java
  leistungstraeger-app/src/main/java/helpers/command/MoveCommand.java
  leistungstraeger-app/src/test/java/application/TestTest.java
  leistungstraeger-app/src/test/java/core/item/ItemStashTest.java
  leistungstraeger-app/src/test/java/core/item/TestItem.java
Labels: backend

#54 Improve ImageLoader
  leistungstraeger-app/src/main/java/DesktopLauncher.java
  leistungstraeger-app/src/main/java/helpers/charactergenerator/CharacterGenerator.java
  leistungstraeger-app/src/main/java/helpers/image/ImageController.java
  leistungstraeger-app/src/main/java/helpers/image/ResourceList.java
  leistungstraeger-app/src/main/resources/images/character_images/character.png
  leistungstraeger-app/src/main/resources/images/default/image_not_found.png
  leistungstraeger-app/src/main/resources/images/room_images/room.png
Labels: frontend, backend

#62 SUD-56-Add_doors
  leistungstraeger-app/src/main/java/DesktopLauncher.java
  leistungstraeger-app/src/main/java/core/character/GameCharacter.java
  leistungstraeger-app/src/main/java/core/character/GameCharacterView.java
  leistungstraeger-app/src/main/java/core/game/Game.java
  leistungstraeger-app/src/main/java/core/game/GameView.java
  leistungstraeger-app/src/main/java/core/game/Turn.java
  leistungstraeger-app/src/main/java/core/item/AbstractItem.java
  leistungstraeger-app/src/main/java/core/object/AbstractObject.java
  leistungstraeger-app/src/main/java/core/object/implementation/AbstractObjectView.java
  leistungstraeger-app/src/main/java/core/object/implementation/Combatable.java
  leistungstraeger-app/src/main/java/core/object/implementation/CombatableView.java
  leistungstraeger-app/src/main/java/core/playingfield/door/Door.java
  leistungstraeger-app/src/main/java/core/playingfield/door/DoorView.java
  leistungstraeger-app/src/main/java/core/playingfield/map/GameMap.java
  leistungstraeger-app/src/main/java/core/playingfield/map/GameMapView.java
  leistungstraeger-app/src/main/java/core/playingfield/room/Room.java
  leistungstraeger-app/src/main/java/core/playingfield/room/RoomView.java
  leistungstraeger-app/src/main/java/core/window/GameWindow.java
  leistungstraeger-app/src/main/java/helpers/charactergenerator/CharacterGenerator.java
  leistungstraeger-app/src/main/java/helpers/command/ChangeRoomCommand.java
  leistungstraeger-app/src/main/java/helpers/command/MoveCommand.java
  leistungstraeger-app/src/main/java/helpers/mouse/MapDragInputHandler.java
  leistungstraeger-app/src/main/java/helpers/mouse/MapMouseInputHandler.java
  leistungstraeger-app/src/main/java/helpers/mouse/MouseButton.java
  leistungstraeger-app/src/main/java/helpers/view/Renderable.java
  leistungstraeger-app/src/main/java/helpers/view/View.java
  leistungstraeger-app/src/main/java/helpers/view/ViewTransformation.java
Labels: backend
